name "blom-rssh"
version "0.0.3"
author "Ørjan Blom"
project_page "https://github.com/blom/puppet-rssh"
source "https://github.com/blom/puppet-rssh"
license "ISC"
summary "rssh module"
description "rssh module"
